name: Push to Replicate

on:
  workflow_dispatch:
    inputs:
      model_name:
        description: 'Enter the model name, like "alice/bunny-detector"'
        required: true

jobs:
  push_to_replicate:
    name: Push to Replicate
    runs-on: ubuntu-latest
    steps:
      - name: Free disk space
        uses: jlumbroso/free-disk-space@v1.3.1
        with:
          tool-cache: false
          docker-images: false

      - name: Checkout
        uses: actions/checkout@v4

      - name: Validate model name
        run: |
          if [[ "${{ inputs.model_name }}" =~ ^r8\.im/ ]]; then
            echo "Error: model_name should not include 'r8.im/'. Use the format '<username>/<model-name>' (e.g., 'alice/bunny-detector')."
            exit 1
          fi
          if ! [[ "${{ inputs.model_name }}" =~ ^[a-zA-Z0-9_-]+/[a-zA-Z0-9_-]+$ ]]; then
            echo "Error: model_name must be in the format '<username>/<model-name>' (e.g., 'alice/bunny-detector')."
            exit 1
          fi

      - name: Setup Cog
        uses: replicate/setup-cog@v2
        with:
          token: ${{ secrets.REPLICATE_CLI_AUTH_TOKEN }}

      - name: Push to Replicate
        run: cog push r8.im/${{ inputs.model_name }}
